Homework 2
ShvargonovaArina/ArinaShvargonova_LevelUp pull request #4
Opened 2023-02-22 20:33 UTC by ShvargonovaArina

2023-03-01 19:54 UTC, khda91 requested changes
Исправить комментарии

2023-03-01 19:54 UTC, khda91 commented on src/main/java/ru/levelp/at/homework2/LuckyTicketCheck.java
> +    public static void main(String[] args) {
`main` метод тут не нужен

2023-03-01 19:54 UTC, khda91 commented on src/main/java/ru/levelp/at/homework2/LuckyTicketCheck.java
> +            return false;
Почему возвращается `false`, а не выбрасывается ошибка?

2023-03-06 13:01 UTC, ShvargonovaArina commented on src/main/java/ru/levelp/at/homework2/LuckyTicketCheck.java
> +    public static void main(String[] args) {
Удалила.

2023-03-06 13:02 UTC, ShvargonovaArina commented on src/main/java/ru/levelp/at/homework2/LuckyTicketCheck.java
> +            return false;
Изменила на ошибку, актуализировала тесты.

2023-03-13 14:37 UTC, khda91 approved these changes
Домашняя работа принята

2023-03-28 04:21 UTC, merged